site_name: Tobias Schulz
theme:
   name: material
   language: en
plugins:
  - search
nav:
  - Introduction: 'index.md'
  - Examples: 'examples.md'
  - Contributing: 'contributing.md'
  - Models: 'models.md'
  - Organization : 'organization.md'
  - Run: 'running.md'
  - Data: 'data.md'
  